### ISSUE TITLE
Form "I want to volunteer"

### ISSUE THREAD

**Issue by egomadking** [opensavannah/opensavannah.org#2]
Form is for SavMaps project, not for general volunteering

**Comment by carlvlewis** [comment]
Feel free to fix that. I'm a bit away from computer.

**Comment by carlvlewis** [comment]
For reference, you'd go to `skills.html` and replace the paperform embed for savmaps with the paperform embed for the general volunteering form. Then issue a PR.

**Comment by carlvlewis** [comment]
Excuse me: You'd go to `skills.md` and change it.

**Comment by egomadking** [comment]
Tracking on that part-

the one thing that is confusing me is that the paperform ID on the
skills.html is a string of random letters. Looking at the form inside
paperform, the ID is the name of the form.


Always assume that you have made some assumptions that others have not.

On August 18, 2017 at 2:25:06 PM, Carl V. Lewis (notifications@github.com)
wrote:

For reference, you'd go to skills.html and replace the paperform embed for
savmaps with the paperform embed for the general volunteering form. Then
issue a PR.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/opensavannah/new.opensavannah.org/issues/2#issuecomment-323426894>,
or mute the thread

**Comment by egomadking** [comment]
I’ll be able to look at it more after work…

-Roy

Always assume that you have made some assumptions that others have not.

On August 18, 2017 at 2:27:26 PM, Roy Mosby (ego.madking@gmail.com) wrote:

Tracking on that part-

the one thing that is confusing me is that the paperform ID on the
skills.html is a string of random letters. Looking at the form inside
paperform, the ID is the name of the form.


Always assume that you have made some assumptions that others have not.

On August 18, 2017 at 2:25:06 PM, Carl V. Lewis (notifications@github.com)
wrote:

For reference, you'd go to skills.html and replace the paperform embed for
savmaps with the paperform embed for the general volunteering form. Then
issue a PR.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/opensavannah/new.opensavannah.org/issues/2#issuecomment-323426894>,
or mute the thread
